package com.resource.energy.domain.xtras;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;

/**
 * Client generated by hbm2java
 * @Author: Adewale Ijalana
 * @Email: adewaleijalana@gmail.com
 */

public interface AppConstant {



    Character NEW_ENTITY = 'N';
    Character DELETE_ENTITY = 'D';
    Character SEEN_ENTITY = 'U';
    String SYSTEM = "SYSTEM";

    interface APP_USER {
        String SYSTEM = "1A39B9B1979648F3832EF1B54F6CF717";
        String SYSTEM_USER_NAME = "a@a.com";
        String SYSTEM_USER_PASSWORD = "1";
    }

    interface AuthorityConstants {
        String AUTH_SERVICE_READ = "AUTH_SERVICE_READ";
        String AUTH_SERVICE_WRITE = "AUTH_SERVICE_WRITE";
        String API_CLIENT = "API_CLIENT";
    }

}
